config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  devise_for :users
  get '/authorizations/:provider/callback', to: 'authorizations#callback'
  get '/authorizations/failure' => 'authorizations#failue', as: :auth_failure
  Setting.omniauth.providers.keys.each do |provider|
    get "/authorizations/#{provider}", as: "auth_#{provider}"
  end

  root to: 'base#index'
  get '/robots.txt', to: 'base#robots', defaults: { format: 'text' }

  namespace :admin do
    root to: 'base#index', as: :root
    resources :users
    resources :categories do
      member do
        get :revisions
        post :restore
      end
    end
  end
end

app/models/admin/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  deleted_at :datetime
#  sort       :integer
#

class Admin::Category < ::Category

  class << self
    def ransackable_scopes(_auth_object = nil)
      [:delete_state, :tagged]
    end
  end
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  deleted_at :datetime
#  sort       :integer
#

class Category < ActiveRecord::Base
  has_paper_trail only: [:name, :deleted_at, :sort]
  sortable column: :sort, add_new_at: nil
  restorable
  taggable

  validates :name, presence: true, uniqueness: true

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :category
  before_action { add_crumb('Categories', admin_categories_path) }

  def index
    @admin_page_title = 'Categories'
    @q = Admin::Category.ransack(params[:q])
    @categories = @q.result.sorted.page(params[:page]).per(30)
    respond_with @categories
  end

  def show
    @admin_page_title = "##{@category.id} #{@category.name}"
    add_crumb @admin_page_title, '#'
  end

  def new
    @admin_page_title = 'New Category'
    add_crumb @admin_page_title, '#'
  end

  def edit
    @admin_page_title = 'Edit Category'
    add_crumb @admin_page_title, '#'
  end

  def revisions
    @admin_page_title = "##{@category.id} #{@category.name} - revisions"
    add_crumb @category.name, admin_category_path(@category)
    add_crumb 'revisions', '#'
    @versions = @category.versions
  end

  def create
    if category.save
      redirect_to params[:redirect_to] || admin_category_path(category), flash: { success: 'category created' }
    else
      new
      flash.now[:error] = category.errors.full_messages
      render :new
    end
  end

  def update
    if category.update_attributes(category_params)
      redirect_to params[:redirect_to] || admin_category_path(category), flash: { success: 'category updated' }
    else
      edit
      flash.now[:error] = category.errors.full_messages
      render :edit
    end
  end

  def destroy
    if category.destroy
      redirect_to params[:redirect_to] || admin_categories_path, flash: { success: 'category deleted' }
    else
      redirect_to :back, flash: { error: category.errors.full_messages }
    end
  end

  def restore
    flash_message = if category.restore
                      { success: 'category restored' }
                    else
                      { error: 'already restored' }
                    end
    redirect_to request.referer || admin_categories_path, flash: flash_message
  end

  private

  def category
    @category ||= params[:id] ? Admin::Category.with_deleted.find(params[:id]) : Admin::Category.new(category_params)
  end

  def category_params
    params.fetch(:category, {}).permit(:name, :tag_list, :sort)
  end

end

app/views/admin/categories/_btns.html.slim
= link_to "Show", admin_category_path(category), class: "btn btn-large"
= link_to "Revisions", revisions_admin_category_path(category), class: "btn btn-large"
= link_to "Edit", edit_admin_category_path(category, redirect_to: url_for(request.params)), class: "btn btn-large btn-success"
= link_to "Delete", admin_category_path(category, redirect_to: ENV['HTTP_REFERER'] || admin_categories_path), class: "btn btn-large btn-danger", method: :delete, "data-confirm" => "Delete?"

app/views/admin/categories/_filtering.html.slim
= search_form_for @q, :builder => SimpleForm::FormBuilder, html: { class: "form-horizontal" }, wrapper: :admin, defaults: { required: false } do |f|
  = f.input :name_cont, label: "name contains"
  = f.input :delete_state, label: "delete state", as: :select, collection: collection_for_delete_state, include_blank: "Without deleted"
  = f.input :tagged, label: "tagged with", as: :select, collection: collection_for_tags, input_html: { "data-select" => true, multiple: true }
  - if Rails.env.development?
    = f.input :created_at_eq, as: :string, input_html: { name: "", value: @q.result.to_sql }, label: "debug sql"
  .form-actions
    = f.submit "Search", class: "btn btn-primary"

app/views/admin/categories/_form.html.slim
= f.input :name
= f.input :tag_list, label: "Tags", as: :string, input_html: { "data-select" => "tags", "data-tags" => collection_for_tags.to_json }
.form-actions
  = f.submit class: "btn btn-primary"

app/views/admin/categories/edit.html.slim
- content_for :btns do
  = render partial: "btns", object: @category, as: :category

= admin_widget_box "Edit Category", icon: :pencil do
  = simple_form_for @category, as: :category, wrapper: :admin do |f|
    = render partial: "form", object: f, as: :f

app/views/admin/categories/index.html.slim
= admin_widget_box "Filtering", icon: :pencil do
  = render partial: "filtering", as: :q, object: @q
= admin_widget_box "Categories", icon: :pencil do
  .dataTables_wrapper
    div
      .dataTables_length
        = link_to "New Category", new_admin_category_path, class: "btn btn-primary btn-mini"
    table.table.table-bordered.table-striped.table-hover
      thead
        tr
          th= "#"
          th= "Name"
          th= "Sort"
          th= "Sorting"
          th= "actions"
      tbody
        - @categories.each do |category|
          tr
            td= category.id
            td= category.name
            td= category.sort
            td
              - unless category.deleted?
                = render_admin_sorting_buttons(category)
            td
              - if category.deleted?
                = link_to "restore", restore_admin_category_path(category), class: "btn btn-mini btn-danger", method: :post, "data-confirm" => "Restore?"
              - else
                = link_to "show", admin_category_path(category), class: "btn btn-mini"
                | &nbsp;
                = link_to "edit", edit_admin_category_path(category), class: "btn btn-mini btn-success"
                | &nbsp;
                = link_to "delete", admin_category_path(category), class: "btn btn-mini btn-danger", method: :delete, "data-confirm" => "Delete?"
    .ui-toolbar.ui-widget-header
      = paginate @categories, theme: :admin

app/views/admin/categories/new.html.slim
= admin_widget_box "New Category", icon: :pencil do
  = simple_form_for @category, as: :category, wrapper: :admin do |f|
    = render partial: "form", object: f, as: :f

app/views/admin/categories/revisions.html.slim
- content_for :btns do
  = render partial: "btns", object: @category, as: :category

= admin_widget_box "Revisions ( total results: #{@versions.size} )", icon: :pencil do
  .dataTables_wrapper
    div
      .dataTables_length
    table.table.table-bordered.table-striped.table-hover
      thead
        tr
          th= "Event"
          th= "When"
          th= "Who"
          th= "What"
      tbody
        - @versions.reverse.each do |version|
          tr
            td= version.event
            td= version.created_at
            td= User.find(version.whodunnit).name rescue version.whodunnit
            td
              - convert_changes_string(version.object_changes).each do |column, diffs|
                .diff= "#{column}: #{diffs[0].nil? ? "NULL" : diffs[0]} -> #{diffs[1].nil? ? "NULL" : diffs[1]}"

app/views/admin/categories/show.html.slim
- content_for :btns do
  = render partial: "btns", object: @category, as: :category
= admin_widget_box "Category ##{@category.id}", icon: :th do
  table.table.table-bordered.table-striped.table-hover
    tbody
      tr
        td= "ID"
        td= @category.id
      tr
        td= "Name"
        td= @category.name
      tr
        td= "Sort"
        td= @category.sort
      tr
        td= "created at"
        td= @category.created_at
      tr
        td= "updated at"
        td= @category.updated_at